In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
# DataFrame oluşturma (kodlar)

stn_boy = np.random.randint(150,190,(10))
stn_kilo = np.random.randint(50,100,(10))
stn_no = np.random.randint(2100,2200,(10))

# pandas kütüphanesi,dictionry veri yapısı üzerine kurulmuştur
# pandas kütüphanesi ile excel ve sql'deki her şeyi yapabilirsiniz.

my_dict = {"ogr_no":stn_no,"ogr_boy":stn_boy,"ogr_kilo":stn_kilo}
my_df = pd.DataFrame.from_dict(my_dict)
my_df


ogr_no  ogr_boy  ogr_kilo
0    2155      150        97
1    2136      179        71
2    2124      166        68
3    2151      157        55
4    2194      156        87
5    2139      177        75
6    2135      167        93
7    2172      161        75
8    2134      180        69
9    2192      187        76

In [5]:
my_df.index

RangeIndex(start=0, stop=10, step=1)

In [6]:
my_df.index = ["Ogrenci_1","Ogrenci_2","Ogrenci_3","Ogrenci_4","Ogrenci_5","Ogrenci_6","Ogrenci_7","Ogrenci_8","Ogrenci_9","Ogrenci_10"]
my_df


ogr_no  ogr_boy  ogr_kilo
Ogrenci_1     2155      150        97
Ogrenci_2     2136      179        71
Ogrenci_3     2124      166        68
Ogrenci_4     2151      157        55
Ogrenci_5     2194      156        87
Ogrenci_6     2139      177        75
Ogrenci_7     2135      167        93
Ogrenci_8     2172      161        75
Ogrenci_9     2134      180        69
Ogrenci_10    2192      187        76

In [7]:
# DataFrame'ye yeni sütun ve deperler ekleme
stn_vize = np.random.randint(20,100,(10))
stn_final = np.random.randint(20,100,(10))

my_df["ogr_vize"] = stn_vize
my_df["ogr_final"] = stn_final
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final
Ogrenci_1     2155      150        97        62         57
Ogrenci_2     2136      179        71        60         42
Ogrenci_3     2124      166        68        79         40
Ogrenci_4     2151      157        55        29         34
Ogrenci_5     2194      156        87        21         37
Ogrenci_6     2139      177        75        27         75
Ogrenci_7     2135      167        93        89         29
Ogrenci_8     2172      161        75        52         58
Ogrenci_9     2134      180        69        81         85
Ogrenci_10    2192      187        76        82         74

In [10]:
deger_vize = my_df["ogr_vize"].values
deger_final = my_df["ogr_final"].values

In [12]:
deger_vize

array([62, 60, 79, 29, 21, 27, 89, 52, 81, 82])

In [13]:
deger_final

array([57, 42, 40, 34, 37, 75, 29, 58, 85, 74])

In [16]:
deger_vize*2

array([124, 120, 158,  58,  42,  54, 178, 104, 162, 164])

In [18]:
# ogr_gecti isimli bir key ekleyin
# bu key'in değerleri vize notlarının yüzde kırkı ile
# final notlarının yüzde altmışının toplam alacak

vize_not = my_df["ogr_vize"].values*0.4
final_not = my_df["ogr_final"].values*0.6

son_not = vize_not+final_not

my_df["ogr_gecti"]=son_not
my_df


ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti
Ogrenci_1     2155      150        97        62         57       59.0
Ogrenci_2     2136      179        71        60         42       49.2
Ogrenci_3     2124      166        68        79         40       55.6
Ogrenci_4     2151      157        55        29         34       32.0
Ogrenci_5     2194      156        87        21         37       30.6
Ogrenci_6     2139      177        75        27         75       55.8
Ogrenci_7     2135      167        93        89         29       53.0
Ogrenci_8     2172      161        75        52         58       55.6
Ogrenci_9     2134      180        69        81         85       83.4
Ogrenci_10    2192      187        76        82         74       77.2

In [19]:
my_df["Durum"] = my_df["ogr_gecti"].values>50
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  Durum
Ogrenci_1     2155      150        97        62         57       59.0   True
Ogrenci_2     2136      179        71        60         42       49.2  False
Ogrenci_3     2124      166        68        79         40       55.6   True
Ogrenci_4     2151      157        55        29         34       32.0  False
Ogrenci_5     2194      156        87        21         37       30.6  False
Ogrenci_6     2139      177        75        27         75       55.8   True
Ogrenci_7     2135      167        93        89         29       53.0   True
Ogrenci_8     2172      161        75        52         58       55.6   True
Ogrenci_9     2134      180        69        81         85       83.4   True
Ogrenci_10    2192      187        76        82         74       77.2   True

In [20]:
my_df["cinsiyet"]="Erkek"
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  Durum  \
Ogrenci_1     2155      150        97        62         57       59.0   True   
Ogrenci_2     2136      179        71        60         42       49.2  False   
Ogrenci_3     2124      166        68        79         40       55.6   True   
Ogrenci_4     2151      157        55        29         34       32.0  False   
Ogrenci_5     2194      156        87        21         37       30.6  False   
Ogrenci_6     2139      177        75        27         75       55.8   True   
Ogrenci_7     2135      167        93        89         29       53.0   True   
Ogrenci_8     2172      161        75        52         58       55.6   True   
Ogrenci_9     2134      180        69        81         85       83.4   True   
Ogrenci_10    2192      187        76        82         74       77.2   True   

           cinsiyet  
Ogrenci_1     Erkek  
Ogrenci_2     Erkek  
Ogrenci_3     Erkek  
Ogrenci_4     Erkek  
Ogrenci_5     Erkek  
Ogrenci_6     Erkek  
Ogrenci_7     Erkek  
Ogrenci_8     Erkek  
Ogrenci_9     Erkek  
Ogrenci_10    Erkek

In [21]:
# istenilen özelliklere göre değer getirme
# tek sorguya göre
my_df[my_df["ogr_vize"]<50]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  Durum  \
Ogrenci_4    2151      157        55        29         34       32.0  False   
Ogrenci_5    2194      156        87        21         37       30.6  False   
Ogrenci_6    2139      177        75        27         75       55.8   True   

          cinsiyet  
Ogrenci_4    Erkek  
Ogrenci_5    Erkek  
Ogrenci_6    Erkek

In [22]:
# Birden fazla sorguya göre değer çağırma
my_df[(my_df["ogr_vize"]<50) & (my_df["Durum"]==True)]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  Durum  \
Ogrenci_6    2139      177        75        27         75       55.8   True   

          cinsiyet  
Ogrenci_6    Erkek

In [23]:
my_ds = sns.load_dataset("titanic")
my_ds

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [25]:
# yabancı bir veri seti gördüğünüzde onu tanımak için 2 hazır fonksiyon
# kullanın=> .info() ve .describe()

my_ds.describe() 

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [27]:
my_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [28]:
my_ds.pivot_table("survived",index="sex",columns="class")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16364\2593529420.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  my_ds.pivot_table("survived",index="sex",columns="class")


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [31]:
my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16364\539266334.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16364\539266334.py:1: FutureWarning: The provided callable <function sum at 0x0000023FFB818C10> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)


class   First  Second  Third
sex                         
female     91      70     72
male       45      17     47

In [39]:
# verileri excel olarak kaydetme

pd.DataFrame.to_excel(my_df,"my_df.xlsx")

In [41]:
pd.DataFrame.to_excel(sorgu,"my_df_pivot_table.xlsx")